language: php

php:
  - 5.6
  - 7.0

git:
  depth: 1

sudo: false

install:
  - composer self-update
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - composer install

script:
  - vendor/bin/phpunit --coverage-text=coverage.txt

after_script:
  - head coverage.txt
