name: code-quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        php-versions: [7.3, 7.4]
        experimental: [false]
        include:
          - php-versions: 8.0
            experimental: true
          - php-versions: 7.2
            experimental: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup PHP with Xdebug
        run: shivammathur/setup-php@v2
        with:
          php-versions: ${{ matrix.php-versions }}
          coverage: xdebug
          extensions: json

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --no-progress --no-suggest

      - name: Run code sniffer
        run: vendor/bin/phpcs --report-summary --report-gitblame .

      - name: Run tests
        run: vendor/bin/phpunit --coverage-text
